### ISSUE TITLE
Since 0.11.1 error during generation

### ISSUE THREAD

**Issue by StefanKoenigMUC** [cyclosproject/ng-openapi-gen#105]
Since upgrading to 0.11.1 generation of client-files fails with this error message:

`Error on API generation from http://localhost:5000/swagger/v1/swagger.json: Error: ENOTEMPTY: directory not empty, rmdir 'src\app\api-client$\models'`

configuration with this parameters
```
{
    "$schema": "node_modules/ng-openapi-gen/ng-openapi-gen-schema.json",
    "input": "http://localhost:5000/swagger/v1/swagger.json",
    "output": "src/app/api-client",
    "ignoreUnusedModels": false,
    "removeStaleFiles": true
  }
```

Additionally files are not generated into the provided folder, instead a new folder postfixed with '$' is created. This behavior appears on Win10. With previous version 0.9.0 everything is still working fine.

generation is started via without any further parameters.

Could you provide any assistance regarding this?

Thanks in advance,
Stefan

**Comment by luisfpg** [comment]
It seems that you're on Windows. I work on Linux, and this issue seems to be related to the OS.
The error is that the directory isn't empty on rmdir. The actual code is in `gen-utils.ts`:
```typescript
export function deleteDirRecursive(dir: string) {
  if (fs.existsSync(dir)) {
    fs.readdirSync(dir).forEach((file: any) => {
      const curPath = path.join(dir, file);
      if (fs.lstatSync(curPath).isDirectory()) { // recurse
        deleteDirRecursive(curPath);
      } else { // delete file
        fs.unlinkSync(curPath);
      }
    });
    fs.rmdirSync(dir);
  }
}
```
So, for each entry in the directory listing, if it is a directory, the function recurses. Otherwise, it should be a regular file, and is deleted with the `unlinkSync` call. Finally, and that is that line that seems to fail, there's the `rmdirSync` call.
Can you add some debugs on it to isolate the problem? See https://github.com/cyclosproject/ng-openapi-gen#developing-and-contributing on how to run a locally linked version.
I'm sorry, but I can't fix the issue directly because I don't use Windows.

**Comment by StefanKoenigMUC** [comment]
thanks, i'll come back to you asap with those details :-)

**Comment by luisfpg** [comment]
Closing for lack of feedback
