### ISSUE TITLE
Response Type changes base on return type

### ISSUE THREAD

**Issue by begrs** [cyclosproject/ng-openapi-gen#166]
The generated code changes the response type base on the return type of the method.
This might have some secret reason, but produces a very hard to find error when working with the generated service.
In my case (see below) it cause the err.error property to be a string, instead of a javascript object (json) and made the whole error handling code fail silently, just because the return type in the asp.net core WebApi changed.
Ofcorse changing the return type causes the response handling code to have to change, but it is unintuitive that the error handling code should change.
What makes the issue worse, is that there are numerous points of failure for an issue like that: the asp.net api, swagger/open-api documentation generation, ng-openapi-gen configration files or even IIS settings. Took me a very long time to find the issue.

I think this behavior should be changed, but for my case having a way to set the default response type used for the whole api would have been sufficient as I only want to use json anyway. My current workaround is just to return the '0' to get a json response ...

Note: The actual namespace and Dto class name was changed in the following code per company policy.

```
[HttpPost("save", Name = nameof(Save))]
        public async Task Save(Dto dto)
        {
            var settings = dto.ToModels(tenant);
            await _userSettingsRepository.Update(settings);
        }
```

The code above produces 
```
  save$Response(params?: {
    body?: Dto
  }): Observable<StrictHttpResponse<void>> {

    const rb = new RequestBuilder(this.rootUrl, DtoService.SavePath, 'post');
    if (params) {
      rb.body(params.body, 'application/*+json');
    }

    return this.http.request(rb.build({
      responseType: 'text',
      accept: '*/*'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
      })
    );
  }
```

while the code

```
[HttpPost("save", Name = nameof(Save))]
        public async Task<int> Save(Dto dto)
        {
            var settings = dto.ToModels(tenant);
            await _userSettingsRepository.Update(settings);

            return 0;
        }
```

produces:
```
save$Response(params?: {
    body?: Dto
  }): Observable<StrictHttpResponse<number>> {

    const rb = new RequestBuilder(this.rootUrl, DtoService.SavePath, 'post');
    if (params) {
      rb.body(params.body, 'application/*+json');
    }

    return this.http.request(rb.build({
      responseType: 'json',
      accept: 'text/json'
    })).pipe(
      filter((r: any) => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
      })
    );
  }
```

**Comment by luisfpg** [comment]
That's how the generator works.
For example, an operation returning a String cannot be set to responseType json, because the parsing would fail.
Unfortunately in the http client module, this also affects the error handling.
See, for example, this response for an example: https://github.com/cyclosproject/ng-openapi-gen/issues/113#issuecomment-645522479

**Comment by begrs** [comment]
If that is the intended behavior, I think an overwrite mechanism to specify the response type would be important.
For an enterprise dev environment I would much rather get an error when the type cannot be parsed. Especially since the typescript type check cant catch this as the HttpResponse is of generic type any (which makes sense, but has bad side effects in cases like this one).
I will add the provided code snippet, but having code like that is a real issue for newly added code by different parties as they might not know to add it if e.g. in the first debug session they inspect the response and build code around what they see.
I think it should at least be added to the general part of the documentation as the behavior.

**Comment by ThomasOrtiz** [comment]
👋 Hey, @luisfpg I think I'm running into a similar issue as @begrs and wanted to explain and double-check if it actually is the same issue.

Our API has this setup:
- **Posts**
  - On 200, return a `application/json` response where response body is the new record id.
  - On 4xx, return a `application/problem+json` where response body is error information.
- **Patch**
  - On 200, return a body-less response. 
  - On 4xx, return a `application/problem+json` where response body is error information.

## Examples
### Post - Create record 
`POST` endpoints in our model generate as we'd expect. This example here is to compare to `PATCH`.

<details>
<summary>Open API doc</summary>

```JSON
{
  "/records": {
    "post": {
      "summary": "Create a record",
      "operationId": "CreateRecord",
      "responses": {
        "200": {
          "description": "Returned when the operation succeeds. The response body will contain an ID.",
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/IdResponse" }
            }
          }
        },
        "400": {
          "description": "Returned when the request is not in the appropriate format.",
          "content": {
            "application/problem+json": {
              "schema": { "$ref": "#/components/schemas/CreateRecord400ResponseTypes" }
            }
          }
        }
      }
    }
  }
}
```
</details>

<details>
<summary>ng-openapi-gen result</summary>

```TS
this.http.request(rb.build({
  responseType: 'json',
  accept: 'application/json',
})
```
</details>

<details>
<summary>400 Error Result</summary>

```JSON
{
    "headers": {
      "normalizedNames": {},
      "lazyUpdate": null
    },
    "status": 400,
    "statusText": "OK",
    "url": "https://example.com/api/records",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for https://example.com/api/records: 400 OK",
    "error": {
      "type": "urn:example:validation-error",
      "title": "One or more validation errors occurred.",
      "status": 400,
      "detail": "Record is invalid",
      "values": {
        "errors": [
          {
            "property_name": "record.id",
            "error_message": "Must be unique",
            "error_code": "MustBeUnique"
          }
        ]
      }
    }
}
```
</details>


### Patch - Edit record
<details>
<summary>Open API doc</summary>

```JSON
{
    "/records/{id}": {
        "patch": {
          "summary": "Edit a record",
          "operationId": "EditRecord",
          "responses": {
            "200": {
              "description": "Returned when the operation succeeds. The response body will contain an ID."
            },
            "400": {
              "description": "Returned when the request is not in the appropriate format.",
              "content": {
                "application/problem+json": {
                  "schema": { "$ref": "#/components/schemas/EditRecord400ResponseTypes" }
                }
              }
            }
          }
        }
      }
}
```
</details>

<details>
<summary>ng-openapi-gen result</summary>

```TS
this.http.request(rb.build({
  responseType: 'text',
  accept: '*/*'
})
```
</details>

<details>
<summary>400 Error Result</summary>

```JSON
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 400,
  "statusText": "OK",
  "url": "https://example.com/api/records",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://example.com/api/records: 400 OK",
  "error": "{\"type\":\"urn:example:validation-error\",\"title\":\"One or more validation errors occurred.\",\"status\":400,\"detail\":\"Record is invalid\",\"values\":{\"errors\":[{\"property_name\":\"record.id\",\"error_message\":\"Must be unique.\",\"error_code\":\"MustBeUnique\"}]} }"
}
```
</details>

## Discussion
In the `PATCH` endpoint it seems like the `400`'s content type of `application/problem+json` is ignored in favor of `200`'s empty content which seemingly maps to `text`. 

This causes the generated `HttpErrorResponse` that Angular creates to parse the error object as a `string` rather than an `object` as it is in the `POST` request above which makes parsing that information rough.

Is this expected or a bug?

**Comment by luisfpg** [comment]
It is as expected. Unfortunately, there's no way to specify distinct responseTypes for distinct HTTP status codes.
The way we do a general error handling is like this: https://github.com/cyclosproject/cyclos4-ui/blob/0adeed887f8b397fa709d872a864df342df37f4c/src/app/core/error-handler.service.ts#L151
We just assume the error can be either a JSON object or a string.

**Comment by ThomasOrtiz** [comment]
Thanks for responding so quick and giving me an example of what your other project does.

After looking around online I understand why it can't be done because of an Angular HttpClient restriction which seems obvious now.

For anyone else who revists this issue here are Angular issues that are related:
- [angular/angular - HttpClient should allow different responseTypes for success response and error response](https://github.com/angular/angular/issues/19148)
- [angular/angular - HttpClient - HttpErrorResponse not json but blob](https://github.com/angular/angular/issues/19888)
