### ISSUE TITLE
Components Object: keys are not forced to adhere to the OpenAPI spec

### ISSUE THREAD

**Issue by Kattoor** [cyclosproject/ng-openapi-gen#179]
Another OpenAPI generator that I'm using for Flutter development made me aware of the following constraint that the OpenAPI spec applies to the keys of the records in the 'Components' object:

[All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.](https://swagger.io/specification)

By omitting this, the ng-openapi-gen project will successfully generate code, even if the input json/yaml file doesn't adhere to the OpenAPI spec.

**Comment by luisfpg** [comment]
To be honest, I wasn't aware of this constraint either.
Anyway, this doesn't affect so much the generator, because it would only affect reusable definitions, which are only referenced elsewhere.
Of course, there are the schemas, which is the most important for us. But the generated model names are normalized anyhow, because `.` and `-` are accepted.
So I don't see a reason to break the generation if any of those fixed names don't comply with the spec's regex.
