### ISSUE TITLE
generate promise version method

### ISSUE THREAD

**Issue by zh99998** [cyclosproject/ng-openapi-gen#266]
Angular make http client return Observable to do complex things, such as cancellation or progress.
But in real world, 99% of api call are simple, just one-shot, send a request, and get json data.

using Observable, many many firstValueFrom() or lastValueFrom() are needed, it's really boring.
Could codgen add a method to call lastValueFrom() internal and just return promise?
It will save developers from lastValueFrom() hell.

**Comment by luisfpg** [comment]
This is out of scope for this project, because "The Angular Way" is with observables.
You can, however, copy the `operationBody.handlebars` template to some folder in your project, edit the `ng-openapi-gen.json` file to set the custom templates folder and edit the template to return a Promise instead of Observable.
