### ISSUE TITLE
Error on generation if the output path has a trailing slash

### ISSUE THREAD

**Issue by felipeplets** [cyclosproject/ng-openapi-gen#66]
On 0.6.x I was not getting this error, but once updating to 0.7.2 I always get the error: 

```Error on API generation from projects/src/app/api-docs/api-docs.yaml: Error: EPERM: operation not permitted, unlink 'projects/src/app/api/generated/$'```

**Comment by luisfpg** [comment]
Just to make sure, try removing the leading `/` from the output setting, so it would be `projects/src/app/api/generated` instead of `projects/src/app/api/generated/`.
Starting with 0.7, the generated files are written to a sibling folder of the output folder, ending with `$`. Then files are synchronized with the output folder, so we no longer remove / rewrite the directory, which caused some issues (see #46).

**Comment by felipeplets** [comment]
@luisfpg perfect, that was exactly my case. Removing the `/` fixed the issue.

**Comment by luisfpg** [comment]
I'm reopening and changing the title to correctly handle the case of a trailing `/` in the output path.
